<?php

namespace Database\Seeders;

use App\Models\Car;
use App\Models\Color;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
            // $car1   = Car::create([
            //     "name_ar" => "مرسيدس S500 4matic 2022",
            //     "name_en" => "mercedes S500 4matic 2022",
            //     "card_description_ar" => "x",
            //     "card_description_en" => "x",
            //     "description_ar" => "Quia ut qui quisquam.",
            //     "description_en" => "Incidunt, accusantiu.",
            //     "main_image" => "webstdy_1647942894mercedes_car_background.jpg",
            //     "cover_image" =>"webstdy_1647942894mercedes_car_background.jpg",
            //     "share_image" => null,
            //     "video_url" => null,
            //     "is_new" => 1,
            //     "distance" => null,
            //     "year" => 2022,
            //     "supplier" => "gulf",
            //     "low_price" => 1,
            //     "status" => 1,
            //     "tax_on_exhibition" => 1,
            //     "tax" => 1,
            //     "price" => 870000,
            //     "discount_price" => null,
            //     "have_discount" => 0,
            //     "price_field_status" => "show",
            //     "price_field_value" => "<h6 class='price-now'> <span class='price-word' ></span>870000<span class='currency-value' ></span> </h6>",
            //     "meta_keywords_ar" => "Aut quis expedita so",
            //     "meta_keywords_en" => "Debitis in iste iste",
            //     "meta_desc_ar" => "Id voluptatem Aliqu",
            //     "meta_desc_en" => "Cupidatat mollitia q",
            //     "speakers_number" => 811,
            //     "seats_number" => 683,
            //     "engine_measurement" => "Id veniam incidunt",
            //     "engine_type" => "Temporibus et conseq",
            //     "valves" => "In perspiciatis nih",
            //     "maximum_force" => "Tempor ipsum quasi q",
            //     "determination" => "Eu nulla molestiae d",
            //     "fuel_consumption" => "2",
            //     "wheels" => "Sunt quidem perspici",
            //     "fuel_tank_capacity" => "Excepturi ullamco re",
            //     "driving_mode" => '["normal"]',
            //     "car_style" => "family",
            //     "traction_type" => "front_wheel",
            //     "Motion_vector" => "auto",
            //     "turbo" => "available",
            //     "engine_system" => "gas",
            //     "steering_wheel" => "electrical_adjustment",
            //     "eco_boost" => "available",
            //     "wheel_shifters" => "available",
            //     "bright_lights_during_the_day" => "unavailable",
            //     "fog_lights" => "unavailable",
            //     "headlights" => "halogen",
            //     "smart_entry_system" => 1,
            //     "chrome_door_handles" => 0,
            //     "rear_parking_sensors" => 0,
            //     "front_parking_sensors" => 0,
            //     "one_touch_electric_sunroof" => 1,
            //     "electrical_side_mirrors" => 0,
            //     "chrome_side_mirrors" => 0,
            //     "automatic_trunk_door" => 0,
            //     "led_backlight_lights" => 1,
            //     "rear_suite" => 1,
            //     "panorama_roof" => 0,
            //     "remote_engine_start" => 0,
            //     "electric_hand_brakes" => 1,
            //     "ac_in_second_row_seats" => 0,
            //     "engine_start_button" => 0,
            //     "cruise_control" => 0,
            //     "leather_steering_wheel" => 0,
            //     "upholstered_seats" => "leather",
            //     "driver_seat_adjustment" => "electrical",
            //     "passenger_seat_movement" => "electrical",
            //     "heated_seats" => 0,
            //     "airy_seats" => 1,
            //     "navigation_system" => 1,
            //     "info_screen" => 0,
            //     "back_screen" => 1,
            //     "cd" => 1,
            //     "bluetooth" => 1,
            //     "mp3" => 0,
            //     "usb_audio_system" => 1,
            //     "apple_carplay_android_auto" => 1,
            //     "hdmi" => 0,
            //     "wireless_charger" => 1,
            //     "front_airbags" => 1,
            //     "side_airbags" => 0,
            //     "knee_airbags" => 1,
            //     "side_curtains" => 1,
            //     "rear_camera" => 0,
            //     "vsa" => 0,
            //     "abs" => 0,
            //     "ebd" => 0,
            //     "ess" => 1,
            //     "ebb" => 1,
            //     "tpms" => 0,
            //     "hsa" => 1,
            //     "ace" => 1,
            //     "track_control_system" => 0,
            //     "display_info_on_windshield" => 0,
            //     "acc" => 1,
            //     "rdm" => 0,
            //     "fcw" => 1,
            //     "blind_spots" => 1,
            //     "lsf" => 0,
            //     "back_traffic_alert" => 1,
            //     "brand_id" => 1,
            //     "model_id" => 1,
            //     "sub_model_id" => 2,
            //     "show_in_home_page" => 1,
            // ]);

            // $car2   = Car::create([
            //     "name_ar" => "بي ام دبليو x3 xdrive 30 i 2021",
            //     "name_en" => "BMW x3 xdrive 30 i 2021",
            //     "card_description_ar" => "bmw",
            //     "card_description_en" => "bmw",
            //     "description_ar" => "Quo suscipit corrupt.",
            //     "description_en" => "Amet, eius nisi ipsa.",
            //     "main_image" =>  "webstdy_1647945032bmw_car_background.jpg",
            //     "cover_image" => "webstdy_1647945032bmw_car_background.jpg",
            //     "share_image" => null,
            //     "video_url" => null,
            //     "is_new" => 0,
            //     "kilometers" => 240,
            //     "distance" => null,
            //     "year" => 2021,
            //     "supplier" => "gulf",
            //     "low_price" => 0,
            //     "status" => 1,
            //     "tax_on_exhibition" => 0,
            //     "tax" => 1,
            //     "price" => 222000,
            //     "discount_price" => 206956,
            //     "have_discount" => 1,
            //     "price_field_status" => "show",
            //     "price_field_value" => "<h6 class='price-before'> <span>222000</span> <span class='currency-value' ></span> </h6>
            //     <h6 class='price-now'> <span class='price-word' ></span>206956<span class='currency-value' ></span> </h6>",
            //     "meta_keywords_ar" => "Accusantium adipisic",
            //     "meta_keywords_en" => "Dolorem sequi non vo",
            //     "meta_desc_ar" => "Explicabo Dicta et",
            //     "meta_desc_en" => "Pariatur Pariatur",
            //     "speakers_number" => 769,
            //     "seats_number" => 47,
            //     "engine_measurement" => "Enim impedit ipsum",
            //     "engine_type" => "Nisi veniam delectu",
            //     "valves" => "Ad qui impedit aut",
            //     "maximum_force" => "Ipsum dolore quia c",
            //     "determination" => "Explicabo Est dolo",
            //     "fuel_consumption" => "3",
            //     "wheels" => "Excepturi at vel rer",
            //     "fuel_tank_capacity" => "In ipsam vel ad aliq",
            //     "driving_mode" => '["normal","sand"]',
            //     "car_style" => "sedan",
            //     "traction_type" => "rear_wheel",
            //     "Motion_vector" => "tiptronic",
            //     "turbo" => "available",
            //     "engine_system" => "hybrid",
            //     "steering_wheel" => "electrical_adjustment",
            //     "eco_boost" => "available",
            //     "wheel_shifters" => "available",
            //     "bright_lights_during_the_day" => "available",
            //     "fog_lights" => "unavailable",
            //     "headlights" => "halogen",
            //     "smart_entry_system" => 1,
            //     "chrome_door_handles" => 1,
            //     "rear_parking_sensors" => 1,
            //     "front_parking_sensors" => 1,
            //     "one_touch_electric_sunroof" => 0,
            //     "electrical_side_mirrors" => 1,
            //     "chrome_side_mirrors" => 1,
            //     "automatic_trunk_door" => 0,
            //     "led_backlight_lights" => 0,
            //     "rear_suite" => 0,
            //     "panorama_roof" => 0,
            //     "remote_engine_start" => 0,
            //     "electric_hand_brakes" => 1,
            //     "ac_in_second_row_seats" => 1,
            //     "engine_start_button" => 0,
            //     "cruise_control" => 1,
            //     "leather_steering_wheel" => 0,
            //     "upholstered_seats" => "leather",
            //     "driver_seat_adjustment" => "electrical",
            //     "passenger_seat_movement" => "manual",
            //     "heated_seats" => 0,
            //     "airy_seats" => 1,
            //     "navigation_system" => 1,
            //     "info_screen" => 0,
            //     "back_screen" => 0,
            //     "cd" => 1,
            //     "bluetooth" => 0,
            //     "mp3" => 1,
            //     "usb_audio_system" => 0,
            //     "apple_carplay_android_auto" => 1,
            //     "hdmi" => 1,
            //     "wireless_charger" => 1,
            //     "front_airbags" => 1,
            //     "side_airbags" => 0,
            //     "knee_airbags" => 0,
            //     "side_curtains" => 1,
            //     "rear_camera" => 1,
            //     "vsa" => 0,
            //     "abs" => 1,
            //     "ebd" => 1,
            //     "ess" => 0,
            //     "ebb" => 0,
            //     "tpms" => 1,
            //     "hsa" => 1,
            //     "ace" => 0,
            //     "track_control_system" => 0,
            //     "display_info_on_windshield" => 1,
            //     "acc" => 0,
            //     "rdm" => 0,
            //     "fcw" => 0,
            //     "blind_spots" => 0,
            //     "lsf" => 0,
            //     "back_traffic_alert" => 1,
            //     "brand_id" => 2,
            //     "model_id" => 3,
            //     "sub_model_id" => 4,
            //     "show_in_home_page" => 1,
            // ]);

            // $colors = Color::get();

            // foreach ( $colors as $color )
            // {
            //     $car1->colors()->attach($color['id'] , ['inner_images' =>  json_encode(['webstdy_1648544016mercedes_car_internal_images_1.jpg','webstdy_1648544016mercedes_car_internal_images_2.jpg','webstdy_1648544016mercedes_car_internal_images_3.jpg']), 'outer_images' => json_encode(['webstdy_1648544016mercedes_car_external_images_4.jpg','webstdy_1648544016mercedes_car_external_images_3.jpg','webstdy_1648544016mercedes_car_external_images_2.jpg'])]);
            //     $car2->colors()->attach($color['id'] , ['inner_images' =>  json_encode(['webstdy_1648022291bmw_car_internal_images_8.jpg','webstdy_1648022291bmw_car_internal_images_4.jpg','webstdy_1648022291bmw_car_internal_images_3b.jpg']), 'outer_images' => json_encode(['webstdy_1647945032bmw_car_external_images_1.jpg','webstdy_1647945032bmw_car_external_images_2.jpg','webstdy_1647945032bmw_car_external_images_3.jpg'])]);
            // }
    }
}
